# Generated by Django 4.1.2 on 2022-10-12 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.CharField(max_length=20)),
                ('cantidadt', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_horas', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.CharField(max_length=1)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.compra_detalle')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=50)),
                ('ruc', models.CharField(max_length=11)),
                ('direcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_de_Medidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cantidad', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Precio_ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preciov', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Precio_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preciop', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Invetariador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_trabajador', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.inventario')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.productos'),
        ),
        migrations.AddField(
            model_name='compra_detalle',
            name='preciop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.precio_proveedor'),
        ),
        migrations.AddField(
            model_name='compra_detalle',
            name='producto_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.producto_proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.proveedor'),
        ),
        migrations.CreateModel(
            name='Caracteristicas_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preciov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.precio_ventas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.productos')),
                ('unidad_de_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenkardex.unidad_de_medidas')),
            ],
        ),
    ]
