# Generated by Django 4.1.2 on 2022-10-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacenkardex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invetariador',
            new_name='Inventariador',
        ),
    ]
